<?php
/**
 * AuditApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eInvoice Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1_8_1_16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * AuditApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AuditApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation auditCount
     *
     * Counts all the results matching the search criteria
     *
     * @param  string $search_criteria_dto_id search_criteria_dto_id (optional)
     * @param  string $search_criteria_dto_virtual_operator MaxLength: 60 (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_start search_criteria_dto_creation_date_start (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_end search_criteria_dto_creation_date_end (optional)
     * @param  string $search_criteria_dto_event_type MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_result_status MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_username MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_property_value MaxLength: 450 (optional)
     * @param  int $search_criteria_dto_offset search_criteria_dto_offset (optional)
     * @param  int $search_criteria_dto_number_of_records search_criteria_dto_number_of_records (optional)
     * @param  string $search_criteria_dto_sort_field search_criteria_dto_sort_field (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return int
     */
    public function auditCount($search_criteria_dto_id = null, $search_criteria_dto_virtual_operator = null, $search_criteria_dto_creation_date_start = null, $search_criteria_dto_creation_date_end = null, $search_criteria_dto_event_type = null, $search_criteria_dto_result_status = null, $search_criteria_dto_username = null, $search_criteria_dto_property_value = null, $search_criteria_dto_offset = null, $search_criteria_dto_number_of_records = null, $search_criteria_dto_sort_field = null)
    {
        list($response) = $this->auditCountWithHttpInfo($search_criteria_dto_id, $search_criteria_dto_virtual_operator, $search_criteria_dto_creation_date_start, $search_criteria_dto_creation_date_end, $search_criteria_dto_event_type, $search_criteria_dto_result_status, $search_criteria_dto_username, $search_criteria_dto_property_value, $search_criteria_dto_offset, $search_criteria_dto_number_of_records, $search_criteria_dto_sort_field);
        return $response;
    }

    /**
     * Operation auditCountWithHttpInfo
     *
     * Counts all the results matching the search criteria
     *
     * @param  string $search_criteria_dto_id (optional)
     * @param  string $search_criteria_dto_virtual_operator MaxLength: 60 (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_start (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_end (optional)
     * @param  string $search_criteria_dto_event_type MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_result_status MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_username MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_property_value MaxLength: 450 (optional)
     * @param  int $search_criteria_dto_offset (optional)
     * @param  int $search_criteria_dto_number_of_records (optional)
     * @param  string $search_criteria_dto_sort_field (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of int, HTTP status code, HTTP response headers (array of strings)
     */
    public function auditCountWithHttpInfo($search_criteria_dto_id = null, $search_criteria_dto_virtual_operator = null, $search_criteria_dto_creation_date_start = null, $search_criteria_dto_creation_date_end = null, $search_criteria_dto_event_type = null, $search_criteria_dto_result_status = null, $search_criteria_dto_username = null, $search_criteria_dto_property_value = null, $search_criteria_dto_offset = null, $search_criteria_dto_number_of_records = null, $search_criteria_dto_sort_field = null)
    {
        $returnType = 'int';
        $request = $this->auditCountRequest($search_criteria_dto_id, $search_criteria_dto_virtual_operator, $search_criteria_dto_creation_date_start, $search_criteria_dto_creation_date_end, $search_criteria_dto_event_type, $search_criteria_dto_result_status, $search_criteria_dto_username, $search_criteria_dto_property_value, $search_criteria_dto_offset, $search_criteria_dto_number_of_records, $search_criteria_dto_sort_field);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'int',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation auditCountAsync
     *
     * Counts all the results matching the search criteria
     *
     * @param  string $search_criteria_dto_id (optional)
     * @param  string $search_criteria_dto_virtual_operator MaxLength: 60 (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_start (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_end (optional)
     * @param  string $search_criteria_dto_event_type MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_result_status MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_username MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_property_value MaxLength: 450 (optional)
     * @param  int $search_criteria_dto_offset (optional)
     * @param  int $search_criteria_dto_number_of_records (optional)
     * @param  string $search_criteria_dto_sort_field (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function auditCountAsync($search_criteria_dto_id = null, $search_criteria_dto_virtual_operator = null, $search_criteria_dto_creation_date_start = null, $search_criteria_dto_creation_date_end = null, $search_criteria_dto_event_type = null, $search_criteria_dto_result_status = null, $search_criteria_dto_username = null, $search_criteria_dto_property_value = null, $search_criteria_dto_offset = null, $search_criteria_dto_number_of_records = null, $search_criteria_dto_sort_field = null)
    {
        return $this->auditCountAsyncWithHttpInfo($search_criteria_dto_id, $search_criteria_dto_virtual_operator, $search_criteria_dto_creation_date_start, $search_criteria_dto_creation_date_end, $search_criteria_dto_event_type, $search_criteria_dto_result_status, $search_criteria_dto_username, $search_criteria_dto_property_value, $search_criteria_dto_offset, $search_criteria_dto_number_of_records, $search_criteria_dto_sort_field)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation auditCountAsyncWithHttpInfo
     *
     * Counts all the results matching the search criteria
     *
     * @param  string $search_criteria_dto_id (optional)
     * @param  string $search_criteria_dto_virtual_operator MaxLength: 60 (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_start (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_end (optional)
     * @param  string $search_criteria_dto_event_type MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_result_status MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_username MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_property_value MaxLength: 450 (optional)
     * @param  int $search_criteria_dto_offset (optional)
     * @param  int $search_criteria_dto_number_of_records (optional)
     * @param  string $search_criteria_dto_sort_field (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function auditCountAsyncWithHttpInfo($search_criteria_dto_id = null, $search_criteria_dto_virtual_operator = null, $search_criteria_dto_creation_date_start = null, $search_criteria_dto_creation_date_end = null, $search_criteria_dto_event_type = null, $search_criteria_dto_result_status = null, $search_criteria_dto_username = null, $search_criteria_dto_property_value = null, $search_criteria_dto_offset = null, $search_criteria_dto_number_of_records = null, $search_criteria_dto_sort_field = null)
    {
        $returnType = 'int';
        $request = $this->auditCountRequest($search_criteria_dto_id, $search_criteria_dto_virtual_operator, $search_criteria_dto_creation_date_start, $search_criteria_dto_creation_date_end, $search_criteria_dto_event_type, $search_criteria_dto_result_status, $search_criteria_dto_username, $search_criteria_dto_property_value, $search_criteria_dto_offset, $search_criteria_dto_number_of_records, $search_criteria_dto_sort_field);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'auditCount'
     *
     * @param  string $search_criteria_dto_id (optional)
     * @param  string $search_criteria_dto_virtual_operator MaxLength: 60 (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_start (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_end (optional)
     * @param  string $search_criteria_dto_event_type MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_result_status MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_username MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_property_value MaxLength: 450 (optional)
     * @param  int $search_criteria_dto_offset (optional)
     * @param  int $search_criteria_dto_number_of_records (optional)
     * @param  string $search_criteria_dto_sort_field (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function auditCountRequest($search_criteria_dto_id = null, $search_criteria_dto_virtual_operator = null, $search_criteria_dto_creation_date_start = null, $search_criteria_dto_creation_date_end = null, $search_criteria_dto_event_type = null, $search_criteria_dto_result_status = null, $search_criteria_dto_username = null, $search_criteria_dto_property_value = null, $search_criteria_dto_offset = null, $search_criteria_dto_number_of_records = null, $search_criteria_dto_sort_field = null)
    {
        if ($search_criteria_dto_virtual_operator !== null && strlen($search_criteria_dto_virtual_operator) > 60) {
            throw new \InvalidArgumentException('invalid length for "$search_criteria_dto_virtual_operator" when calling AuditApi.auditCount, must be smaller than or equal to 60.');
        }

        if ($search_criteria_dto_event_type !== null && strlen($search_criteria_dto_event_type) > 100) {
            throw new \InvalidArgumentException('invalid length for "$search_criteria_dto_event_type" when calling AuditApi.auditCount, must be smaller than or equal to 100.');
        }

        if ($search_criteria_dto_result_status !== null && strlen($search_criteria_dto_result_status) > 100) {
            throw new \InvalidArgumentException('invalid length for "$search_criteria_dto_result_status" when calling AuditApi.auditCount, must be smaller than or equal to 100.');
        }

        if ($search_criteria_dto_username !== null && strlen($search_criteria_dto_username) > 100) {
            throw new \InvalidArgumentException('invalid length for "$search_criteria_dto_username" when calling AuditApi.auditCount, must be smaller than or equal to 100.');
        }

        if ($search_criteria_dto_property_value !== null && strlen($search_criteria_dto_property_value) > 450) {
            throw new \InvalidArgumentException('invalid length for "$search_criteria_dto_property_value" when calling AuditApi.auditCount, must be smaller than or equal to 450.');
        }


        $resourcePath = '/api/audit/count';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($search_criteria_dto_id !== null) {
            $queryParams['searchCriteriaDto.id'] = ObjectSerializer::toQueryValue($search_criteria_dto_id);
        }
        // query params
        if ($search_criteria_dto_virtual_operator !== null) {
            $queryParams['searchCriteriaDto.virtualOperator'] = ObjectSerializer::toQueryValue($search_criteria_dto_virtual_operator);
        }
        // query params
        if ($search_criteria_dto_creation_date_start !== null) {
            $queryParams['searchCriteriaDto.creationDateStart'] = ObjectSerializer::toQueryValue($search_criteria_dto_creation_date_start);
        }
        // query params
        if ($search_criteria_dto_creation_date_end !== null) {
            $queryParams['searchCriteriaDto.creationDateEnd'] = ObjectSerializer::toQueryValue($search_criteria_dto_creation_date_end);
        }
        // query params
        if ($search_criteria_dto_event_type !== null) {
            $queryParams['searchCriteriaDto.eventType'] = ObjectSerializer::toQueryValue($search_criteria_dto_event_type);
        }
        // query params
        if ($search_criteria_dto_result_status !== null) {
            $queryParams['searchCriteriaDto.resultStatus'] = ObjectSerializer::toQueryValue($search_criteria_dto_result_status);
        }
        // query params
        if ($search_criteria_dto_username !== null) {
            $queryParams['searchCriteriaDto.username'] = ObjectSerializer::toQueryValue($search_criteria_dto_username);
        }
        // query params
        if ($search_criteria_dto_property_value !== null) {
            $queryParams['searchCriteriaDto.propertyValue'] = ObjectSerializer::toQueryValue($search_criteria_dto_property_value);
        }
        // query params
        if ($search_criteria_dto_offset !== null) {
            $queryParams['searchCriteriaDto.offset'] = ObjectSerializer::toQueryValue($search_criteria_dto_offset);
        }
        // query params
        if ($search_criteria_dto_number_of_records !== null) {
            $queryParams['searchCriteriaDto.numberOfRecords'] = ObjectSerializer::toQueryValue($search_criteria_dto_number_of_records);
        }
        // query params
        if ($search_criteria_dto_sort_field !== null) {
            $queryParams['searchCriteriaDto.sortField'] = ObjectSerializer::toQueryValue($search_criteria_dto_sort_field);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation auditDetails
     *
     * Gets a specific Audit entry by id
     *
     * @param  string $id  (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\AuditEntryDTO
     */
    public function auditDetails($id)
    {
        list($response) = $this->auditDetailsWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation auditDetailsWithHttpInfo
     *
     * Gets a specific Audit entry by id
     *
     * @param  string $id  (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\AuditEntryDTO, HTTP status code, HTTP response headers (array of strings)
     */
    public function auditDetailsWithHttpInfo($id)
    {
        $returnType = '\Swagger\Client\Model\AuditEntryDTO';
        $request = $this->auditDetailsRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\AuditEntryDTO',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation auditDetailsAsync
     *
     * Gets a specific Audit entry by id
     *
     * @param  string $id  (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function auditDetailsAsync($id)
    {
        return $this->auditDetailsAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation auditDetailsAsyncWithHttpInfo
     *
     * Gets a specific Audit entry by id
     *
     * @param  string $id  (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function auditDetailsAsyncWithHttpInfo($id)
    {
        $returnType = '\Swagger\Client\Model\AuditEntryDTO';
        $request = $this->auditDetailsRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'auditDetails'
     *
     * @param  string $id  (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function auditDetailsRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling auditDetails'
            );
        }

        $resourcePath = '/api/audit/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation auditSearch
     *
     * Get all audit entries that match the search criteria
     *
     * @param  string $search_criteria_dto_id search_criteria_dto_id (optional)
     * @param  string $search_criteria_dto_virtual_operator MaxLength: 60 (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_start search_criteria_dto_creation_date_start (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_end search_criteria_dto_creation_date_end (optional)
     * @param  string $search_criteria_dto_event_type MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_result_status MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_username MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_property_value MaxLength: 450 (optional)
     * @param  int $search_criteria_dto_offset search_criteria_dto_offset (optional)
     * @param  int $search_criteria_dto_number_of_records search_criteria_dto_number_of_records (optional)
     * @param  string $search_criteria_dto_sort_field search_criteria_dto_sort_field (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\AuditEntryDTO[]
     */
    public function auditSearch($search_criteria_dto_id = null, $search_criteria_dto_virtual_operator = null, $search_criteria_dto_creation_date_start = null, $search_criteria_dto_creation_date_end = null, $search_criteria_dto_event_type = null, $search_criteria_dto_result_status = null, $search_criteria_dto_username = null, $search_criteria_dto_property_value = null, $search_criteria_dto_offset = null, $search_criteria_dto_number_of_records = null, $search_criteria_dto_sort_field = null)
    {
        list($response) = $this->auditSearchWithHttpInfo($search_criteria_dto_id, $search_criteria_dto_virtual_operator, $search_criteria_dto_creation_date_start, $search_criteria_dto_creation_date_end, $search_criteria_dto_event_type, $search_criteria_dto_result_status, $search_criteria_dto_username, $search_criteria_dto_property_value, $search_criteria_dto_offset, $search_criteria_dto_number_of_records, $search_criteria_dto_sort_field);
        return $response;
    }

    /**
     * Operation auditSearchWithHttpInfo
     *
     * Get all audit entries that match the search criteria
     *
     * @param  string $search_criteria_dto_id (optional)
     * @param  string $search_criteria_dto_virtual_operator MaxLength: 60 (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_start (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_end (optional)
     * @param  string $search_criteria_dto_event_type MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_result_status MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_username MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_property_value MaxLength: 450 (optional)
     * @param  int $search_criteria_dto_offset (optional)
     * @param  int $search_criteria_dto_number_of_records (optional)
     * @param  string $search_criteria_dto_sort_field (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\AuditEntryDTO[], HTTP status code, HTTP response headers (array of strings)
     */
    public function auditSearchWithHttpInfo($search_criteria_dto_id = null, $search_criteria_dto_virtual_operator = null, $search_criteria_dto_creation_date_start = null, $search_criteria_dto_creation_date_end = null, $search_criteria_dto_event_type = null, $search_criteria_dto_result_status = null, $search_criteria_dto_username = null, $search_criteria_dto_property_value = null, $search_criteria_dto_offset = null, $search_criteria_dto_number_of_records = null, $search_criteria_dto_sort_field = null)
    {
        $returnType = '\Swagger\Client\Model\AuditEntryDTO[]';
        $request = $this->auditSearchRequest($search_criteria_dto_id, $search_criteria_dto_virtual_operator, $search_criteria_dto_creation_date_start, $search_criteria_dto_creation_date_end, $search_criteria_dto_event_type, $search_criteria_dto_result_status, $search_criteria_dto_username, $search_criteria_dto_property_value, $search_criteria_dto_offset, $search_criteria_dto_number_of_records, $search_criteria_dto_sort_field);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\AuditEntryDTO[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation auditSearchAsync
     *
     * Get all audit entries that match the search criteria
     *
     * @param  string $search_criteria_dto_id (optional)
     * @param  string $search_criteria_dto_virtual_operator MaxLength: 60 (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_start (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_end (optional)
     * @param  string $search_criteria_dto_event_type MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_result_status MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_username MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_property_value MaxLength: 450 (optional)
     * @param  int $search_criteria_dto_offset (optional)
     * @param  int $search_criteria_dto_number_of_records (optional)
     * @param  string $search_criteria_dto_sort_field (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function auditSearchAsync($search_criteria_dto_id = null, $search_criteria_dto_virtual_operator = null, $search_criteria_dto_creation_date_start = null, $search_criteria_dto_creation_date_end = null, $search_criteria_dto_event_type = null, $search_criteria_dto_result_status = null, $search_criteria_dto_username = null, $search_criteria_dto_property_value = null, $search_criteria_dto_offset = null, $search_criteria_dto_number_of_records = null, $search_criteria_dto_sort_field = null)
    {
        return $this->auditSearchAsyncWithHttpInfo($search_criteria_dto_id, $search_criteria_dto_virtual_operator, $search_criteria_dto_creation_date_start, $search_criteria_dto_creation_date_end, $search_criteria_dto_event_type, $search_criteria_dto_result_status, $search_criteria_dto_username, $search_criteria_dto_property_value, $search_criteria_dto_offset, $search_criteria_dto_number_of_records, $search_criteria_dto_sort_field)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation auditSearchAsyncWithHttpInfo
     *
     * Get all audit entries that match the search criteria
     *
     * @param  string $search_criteria_dto_id (optional)
     * @param  string $search_criteria_dto_virtual_operator MaxLength: 60 (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_start (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_end (optional)
     * @param  string $search_criteria_dto_event_type MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_result_status MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_username MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_property_value MaxLength: 450 (optional)
     * @param  int $search_criteria_dto_offset (optional)
     * @param  int $search_criteria_dto_number_of_records (optional)
     * @param  string $search_criteria_dto_sort_field (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function auditSearchAsyncWithHttpInfo($search_criteria_dto_id = null, $search_criteria_dto_virtual_operator = null, $search_criteria_dto_creation_date_start = null, $search_criteria_dto_creation_date_end = null, $search_criteria_dto_event_type = null, $search_criteria_dto_result_status = null, $search_criteria_dto_username = null, $search_criteria_dto_property_value = null, $search_criteria_dto_offset = null, $search_criteria_dto_number_of_records = null, $search_criteria_dto_sort_field = null)
    {
        $returnType = '\Swagger\Client\Model\AuditEntryDTO[]';
        $request = $this->auditSearchRequest($search_criteria_dto_id, $search_criteria_dto_virtual_operator, $search_criteria_dto_creation_date_start, $search_criteria_dto_creation_date_end, $search_criteria_dto_event_type, $search_criteria_dto_result_status, $search_criteria_dto_username, $search_criteria_dto_property_value, $search_criteria_dto_offset, $search_criteria_dto_number_of_records, $search_criteria_dto_sort_field);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'auditSearch'
     *
     * @param  string $search_criteria_dto_id (optional)
     * @param  string $search_criteria_dto_virtual_operator MaxLength: 60 (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_start (optional)
     * @param  \DateTime $search_criteria_dto_creation_date_end (optional)
     * @param  string $search_criteria_dto_event_type MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_result_status MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_username MaxLength: 100 (optional)
     * @param  string $search_criteria_dto_property_value MaxLength: 450 (optional)
     * @param  int $search_criteria_dto_offset (optional)
     * @param  int $search_criteria_dto_number_of_records (optional)
     * @param  string $search_criteria_dto_sort_field (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function auditSearchRequest($search_criteria_dto_id = null, $search_criteria_dto_virtual_operator = null, $search_criteria_dto_creation_date_start = null, $search_criteria_dto_creation_date_end = null, $search_criteria_dto_event_type = null, $search_criteria_dto_result_status = null, $search_criteria_dto_username = null, $search_criteria_dto_property_value = null, $search_criteria_dto_offset = null, $search_criteria_dto_number_of_records = null, $search_criteria_dto_sort_field = null)
    {
        if ($search_criteria_dto_virtual_operator !== null && strlen($search_criteria_dto_virtual_operator) > 60) {
            throw new \InvalidArgumentException('invalid length for "$search_criteria_dto_virtual_operator" when calling AuditApi.auditSearch, must be smaller than or equal to 60.');
        }

        if ($search_criteria_dto_event_type !== null && strlen($search_criteria_dto_event_type) > 100) {
            throw new \InvalidArgumentException('invalid length for "$search_criteria_dto_event_type" when calling AuditApi.auditSearch, must be smaller than or equal to 100.');
        }

        if ($search_criteria_dto_result_status !== null && strlen($search_criteria_dto_result_status) > 100) {
            throw new \InvalidArgumentException('invalid length for "$search_criteria_dto_result_status" when calling AuditApi.auditSearch, must be smaller than or equal to 100.');
        }

        if ($search_criteria_dto_username !== null && strlen($search_criteria_dto_username) > 100) {
            throw new \InvalidArgumentException('invalid length for "$search_criteria_dto_username" when calling AuditApi.auditSearch, must be smaller than or equal to 100.');
        }

        if ($search_criteria_dto_property_value !== null && strlen($search_criteria_dto_property_value) > 450) {
            throw new \InvalidArgumentException('invalid length for "$search_criteria_dto_property_value" when calling AuditApi.auditSearch, must be smaller than or equal to 450.');
        }


        $resourcePath = '/api/audit';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($search_criteria_dto_id !== null) {
            $queryParams['searchCriteriaDto.id'] = ObjectSerializer::toQueryValue($search_criteria_dto_id);
        }
        // query params
        if ($search_criteria_dto_virtual_operator !== null) {
            $queryParams['searchCriteriaDto.virtualOperator'] = ObjectSerializer::toQueryValue($search_criteria_dto_virtual_operator);
        }
        // query params
        if ($search_criteria_dto_creation_date_start !== null) {
            $queryParams['searchCriteriaDto.creationDateStart'] = ObjectSerializer::toQueryValue($search_criteria_dto_creation_date_start);
        }
        // query params
        if ($search_criteria_dto_creation_date_end !== null) {
            $queryParams['searchCriteriaDto.creationDateEnd'] = ObjectSerializer::toQueryValue($search_criteria_dto_creation_date_end);
        }
        // query params
        if ($search_criteria_dto_event_type !== null) {
            $queryParams['searchCriteriaDto.eventType'] = ObjectSerializer::toQueryValue($search_criteria_dto_event_type);
        }
        // query params
        if ($search_criteria_dto_result_status !== null) {
            $queryParams['searchCriteriaDto.resultStatus'] = ObjectSerializer::toQueryValue($search_criteria_dto_result_status);
        }
        // query params
        if ($search_criteria_dto_username !== null) {
            $queryParams['searchCriteriaDto.username'] = ObjectSerializer::toQueryValue($search_criteria_dto_username);
        }
        // query params
        if ($search_criteria_dto_property_value !== null) {
            $queryParams['searchCriteriaDto.propertyValue'] = ObjectSerializer::toQueryValue($search_criteria_dto_property_value);
        }
        // query params
        if ($search_criteria_dto_offset !== null) {
            $queryParams['searchCriteriaDto.offset'] = ObjectSerializer::toQueryValue($search_criteria_dto_offset);
        }
        // query params
        if ($search_criteria_dto_number_of_records !== null) {
            $queryParams['searchCriteriaDto.numberOfRecords'] = ObjectSerializer::toQueryValue($search_criteria_dto_number_of_records);
        }
        // query params
        if ($search_criteria_dto_sort_field !== null) {
            $queryParams['searchCriteriaDto.sortField'] = ObjectSerializer::toQueryValue($search_criteria_dto_sort_field);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
