<?php
/**
 * BusinessStatusOutputDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eInvoice Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1_8_1_16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BusinessStatusOutputDtoTest Class Doc Comment
 *
 * @category    Class */
// * @description BusinessStatusOutputDto
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BusinessStatusOutputDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BusinessStatusOutputDto"
     */
    public function testBusinessStatusOutputDto()
    {
    }

    /**
     * Test attribute "status_date"
     */
    public function testPropertyStatusDate()
    {
    }

    /**
     * Test attribute "status_type"
     */
    public function testPropertyStatusType()
    {
    }

    /**
     * Test attribute "status_reason"
     */
    public function testPropertyStatusReason()
    {
    }

    /**
     * Test attribute "status_updated_by"
     */
    public function testPropertyStatusUpdatedBy()
    {
    }
}
