<?php
/**
 * DebitNoteInputDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eInvoice Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1_8_1_16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DebitNoteInputDtoTest Class Doc Comment
 *
 * @category    Class */
// * @description Represents an DebitNote input DTO.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DebitNoteInputDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DebitNoteInputDto"
     */
    public function testDebitNoteInputDto()
    {
    }

    /**
     * Test attribute "serie_prefix"
     */
    public function testPropertySeriePrefix()
    {
    }

    /**
     * Test attribute "serie_number"
     */
    public function testPropertySerieNumber()
    {
    }

    /**
     * Test attribute "delivery_date"
     */
    public function testPropertyDeliveryDate()
    {
    }

    /**
     * Test attribute "billing_period"
     */
    public function testPropertyBillingPeriod()
    {
    }

    /**
     * Test attribute "document_references"
     */
    public function testPropertyDocumentReferences()
    {
    }

    /**
     * Test attribute "reason_debit"
     */
    public function testPropertyReasonDebit()
    {
    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "prepaid_payments"
     */
    public function testPropertyPrepaidPayments()
    {
    }

    /**
     * Test attribute "issuer_party"
     */
    public function testPropertyIssuerParty()
    {
    }

    /**
     * Test attribute "customer_party"
     */
    public function testPropertyCustomerParty()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "lines"
     */
    public function testPropertyLines()
    {
    }

    /**
     * Test attribute "tax_summaries"
     */
    public function testPropertyTaxSummaries()
    {
    }

    /**
     * Test attribute "withholding_tax_summaries"
     */
    public function testPropertyWithholdingTaxSummaries()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "issue_mode"
     */
    public function testPropertyIssueMode()
    {
    }

    /**
     * Test attribute "issue_date"
     */
    public function testPropertyIssueDate()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "external_reference"
     */
    public function testPropertyExternalReference()
    {
    }

    /**
     * Test attribute "correlation_document_id"
     */
    public function testPropertyCorrelationDocumentId()
    {
    }

    /**
     * Test attribute "serie_external_key"
     */
    public function testPropertySerieExternalKey()
    {
    }

    /**
     * Test attribute "additional_notification_emails"
     */
    public function testPropertyAdditionalNotificationEmails()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "attachments"
     */
    public function testPropertyAttachments()
    {
    }

    /**
     * Test attribute "pdf"
     */
    public function testPropertyPdf()
    {
    }
}
