<?php
/**
 * InboundDocumentOutputDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eInvoice Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1_8_1_16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InboundDocumentOutputDtoTest Class Doc Comment
 *
 * @category    Class */
// * @description Dto of an inbound document.
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InboundDocumentOutputDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InboundDocumentOutputDto"
     */
    public function testInboundDocumentOutputDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "document_number"
     */
    public function testPropertyDocumentNumber()
    {
    }

    /**
     * Test attribute "document_type"
     */
    public function testPropertyDocumentType()
    {
    }

    /**
     * Test attribute "document_sub_type"
     */
    public function testPropertyDocumentSubType()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "document_date"
     */
    public function testPropertyDocumentDate()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "issuer_name"
     */
    public function testPropertyIssuerName()
    {
    }

    /**
     * Test attribute "customer_name"
     */
    public function testPropertyCustomerName()
    {
    }

    /**
     * Test attribute "business_status"
     */
    public function testPropertyBusinessStatus()
    {
    }

    /**
     * Test attribute "total_amount"
     */
    public function testPropertyTotalAmount()
    {
    }

    /**
     * Test attribute "business_status_reason"
     */
    public function testPropertyBusinessStatusReason()
    {
    }

    /**
     * Test attribute "possibly_tacitly_accepted"
     */
    public function testPropertyPossiblyTacitlyAccepted()
    {
    }

    /**
     * Test attribute "pdf"
     */
    public function testPropertyPdf()
    {
    }

    /**
     * Test attribute "xml"
     */
    public function testPropertyXml()
    {
    }

    /**
     * Test attribute "document_attachments"
     */
    public function testPropertyDocumentAttachments()
    {
    }
}
