<?php
/**
 * LegalMonetaryTotalDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eInvoice Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1_7_0_4
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LegalMonetaryTotalDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description LegalMonetaryTotalDTO
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LegalMonetaryTotalDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LegalMonetaryTotalDTO"
     */
    public function testLegalMonetaryTotalDTO()
    {
    }

    /**
     * Test attribute "gross_amount"
     */
    public function testPropertyGrossAmount()
    {
    }

    /**
     * Test attribute "payable_amount"
     */
    public function testPropertyPayableAmount()
    {
    }

    /**
     * Test attribute "taxable_amount"
     */
    public function testPropertyTaxableAmount()
    {
    }

    /**
     * Test attribute "allowances_total_amount"
     */
    public function testPropertyAllowancesTotalAmount()
    {
    }

    /**
     * Test attribute "charges_total_amount"
     */
    public function testPropertyChargesTotalAmount()
    {
    }
}
