<?php
/**
 * OutboundDocumentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eInvoice Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1_8_1_16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OutboundDocumentTest Class Doc Comment
 *
 * @category    Class */
// * @description OutboundDocument
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OutboundDocumentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OutboundDocument"
     */
    public function testOutboundDocument()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "serie_number"
     */
    public function testPropertySerieNumber()
    {
    }

    /**
     * Test attribute "serie_prefix"
     */
    public function testPropertySeriePrefix()
    {
    }

    /**
     * Test attribute "issue_date"
     */
    public function testPropertyIssueDate()
    {
    }

    /**
     * Test attribute "billing_period"
     */
    public function testPropertyBillingPeriod()
    {
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "lines"
     */
    public function testPropertyLines()
    {
    }

    /**
     * Test attribute "tax_summary"
     */
    public function testPropertyTaxSummary()
    {
    }

    /**
     * Test attribute "withholding_tax_summary"
     */
    public function testPropertyWithholdingTaxSummary()
    {
    }

    /**
     * Test attribute "prepaid_payments"
     */
    public function testPropertyPrepaidPayments()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "document_type"
     */
    public function testPropertyDocumentType()
    {
    }

    /**
     * Test attribute "document_sub_type"
     */
    public function testPropertyDocumentSubType()
    {
    }

    /**
     * Test attribute "cufe"
     */
    public function testPropertyCufe()
    {
    }

    /**
     * Test attribute "cufe_unhashed"
     */
    public function testPropertyCufeUnhashed()
    {
    }

    /**
     * Test attribute "business_status"
     */
    public function testPropertyBusinessStatus()
    {
    }

    /**
     * Test attribute "communication_status"
     */
    public function testPropertyCommunicationStatus()
    {
    }

    /**
     * Test attribute "document_references"
     */
    public function testPropertyDocumentReferences()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "issue_mode"
     */
    public function testPropertyIssueMode()
    {
    }

    /**
     * Test attribute "external_reference"
     */
    public function testPropertyExternalReference()
    {
    }

    /**
     * Test attribute "payment_means"
     */
    public function testPropertyPaymentMeans()
    {
    }

    /**
     * Test attribute "payment_terms"
     */
    public function testPropertyPaymentTerms()
    {
    }

    /**
     * Test attribute "delivery_terms"
     */
    public function testPropertyDeliveryTerms()
    {
    }

    /**
     * Test attribute "allowance_charges"
     */
    public function testPropertyAllowanceCharges()
    {
    }

    /**
     * Test attribute "payment_exchange_rate"
     */
    public function testPropertyPaymentExchangeRate()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "delivery_date"
     */
    public function testPropertyDeliveryDate()
    {
    }

    /**
     * Test attribute "serie_id"
     */
    public function testPropertySerieId()
    {
    }

    /**
     * Test attribute "correlation_document_id"
     */
    public function testPropertyCorrelationDocumentId()
    {
    }

    /**
     * Test attribute "in_transport_document_id"
     */
    public function testPropertyInTransportDocumentId()
    {
    }

    /**
     * Test attribute "issuer_party_id"
     */
    public function testPropertyIssuerPartyId()
    {
    }

    /**
     * Test attribute "customer_party_id"
     */
    public function testPropertyCustomerPartyId()
    {
    }

    /**
     * Test attribute "pdf_template_id"
     */
    public function testPropertyPdfTemplateId()
    {
    }

    /**
     * Test attribute "virtual_operator_id"
     */
    public function testPropertyVirtualOperatorId()
    {
    }

    /**
     * Test attribute "virtual_operator"
     */
    public function testPropertyVirtualOperator()
    {
    }

    /**
     * Test attribute "issuer_party"
     */
    public function testPropertyIssuerParty()
    {
    }

    /**
     * Test attribute "customer_party"
     */
    public function testPropertyCustomerParty()
    {
    }

    /**
     * Test attribute "document_files"
     */
    public function testPropertyDocumentFiles()
    {
    }

    /**
     * Test attribute "dian_communication_responses"
     */
    public function testPropertyDianCommunicationResponses()
    {
    }

    /**
     * Test attribute "serie"
     */
    public function testPropertySerie()
    {
    }

    /**
     * Test attribute "pdf_template"
     */
    public function testPropertyPdfTemplate()
    {
    }

    /**
     * Test attribute "document_emails"
     */
    public function testPropertyDocumentEmails()
    {
    }

    /**
     * Test attribute "document_attachments"
     */
    public function testPropertyDocumentAttachments()
    {
    }

    /**
     * Test attribute "issuer_contacts"
     */
    public function testPropertyIssuerContacts()
    {
    }

    /**
     * Test attribute "customer_contacts"
     */
    public function testPropertyCustomerContacts()
    {
    }

    /**
     * Test attribute "contingency_data"
     */
    public function testPropertyContingencyData()
    {
    }

    /**
     * Test attribute "software_security_code"
     */
    public function testPropertySoftwareSecurityCode()
    {
    }

    /**
     * Test attribute "public_document_url"
     */
    public function testPropertyPublicDocumentUrl()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "last_update_date"
     */
    public function testPropertyLastUpdateDate()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }
}
