<?php
/**
 * InboundDocumentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * eInvoice Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1_8_1_16
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * InboundDocumentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InboundDocumentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for inboundDocumentAccept
     *
     * Accepts a outboundDocument.
     *
     */
    public function testInboundDocumentAccept()
    {
    }

    /**
     * Test case for inboundDocumentAddAttachment
     *
     * Adds a manual attachment to the inbound document.
     *
     */
    public function testInboundDocumentAddAttachment()
    {
    }

    /**
     * Test case for inboundDocumentAttachment
     *
     * Gets an attachment.
     *
     */
    public function testInboundDocumentAttachment()
    {
    }

    /**
     * Test case for inboundDocumentAttachmentContent
     *
     * Get an attachment content.
     *
     */
    public function testInboundDocumentAttachmentContent()
    {
    }

    /**
     * Test case for inboundDocumentCount
     *
     * Counts documents using search criteria.
     *
     */
    public function testInboundDocumentCount()
    {
    }

    /**
     * Test case for inboundDocumentCreateDocument
     *
     * Upload a received document..
     *
     */
    public function testInboundDocumentCreateDocument()
    {
    }

    /**
     * Test case for inboundDocumentDocumentFile
     *
     * Gets a file.
     *
     */
    public function testInboundDocumentDocumentFile()
    {
    }

    /**
     * Test case for inboundDocumentFileContent
     *
     * Get a file content.
     *
     */
    public function testInboundDocumentFileContent()
    {
    }

    /**
     * Test case for inboundDocumentGet
     *
     * Get the detail of a specific document based on specific Id.
     *
     */
    public function testInboundDocumentGet()
    {
    }

    /**
     * Test case for inboundDocumentReject
     *
     * Rejects a outboundDocument.
     *
     */
    public function testInboundDocumentReject()
    {
    }

    /**
     * Test case for inboundDocumentRemoveAttachment
     *
     * Deletes a manual attachment of an inbound document.
     *
     */
    public function testInboundDocumentRemoveAttachment()
    {
    }

    /**
     * Test case for inboundDocumentSearch
     *
     * Search documents using search criteria  Default NumberOfRecords=25.
     *
     */
    public function testInboundDocumentSearch()
    {
    }

    /**
     * Test case for inboundDocumentUploadFilePdf
     *
     * Uploads the Pdf file to the inbound document.
     *
     */
    public function testInboundDocumentUploadFilePdf()
    {
    }
}
